name: CI
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:

  run-terraform:
    name: 'Run terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.ROLE_ASSUME }}
      - name: Setup terraform
        uses: 'hashicorp/setup-terraform@v3'
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Terraform format
        run: terraform fmt

      - name: Terraform format check
        run: terraform fmt -check

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        run: terraform apply -auto-approve